[profile.default]
src = "src"
test = "test"
out = "out"
cache_path = "cache"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1
via_ir = true
auto_detect_remappings = false
allow_internal_expect_revert = true
gas_limit = "300000000"

[profile.default.fuzz]
runs = 256

[rpc_endpoints]
bsc = "${BSC_RPC_URL}"
